name: Documentação Zensical CI/CD

on:
  push:
    [cite_start]branches: [ "main" ] 
  pull_request:
    [cite_start]branches: [ "main" ] 
  schedule:
    - [cite_start]cron: '0 0 * * 0'  

jobs:
  build_site:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        [cite_start]python-version: ["3.10", "3.11"]

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: ⚡ Cache das dependências do Pip
        uses: actions/cache@v4
        with:
          [cite_start]path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 📦 Instalar dependências
        run: pip install -r requirements.txt 

      - name: 🏗️ Fazer o Build do Site Zensical
        run: zensical Build

      - name: 📤 Fazer Upload do Artefato (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: site-docs-python-${{ matrix.python-version }}
          path: site/

  deploy_site:
    [cite_start]needs: build_site 
    if: github.event_name == 'push' || github.event_name == 'schedule' 
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Fazer Download do Artefato
        uses: actions/download-artifact@v4
        with:
          [cite_start]name: site-docs-python-3.11 
          path: site/

      - name: 🚀 Publicar no GitHub Pages
        [cite_start]uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site 